<?xml version="1.0"?>
<package format="3">
  <name>webrtc_ros</name>
  <version>59.0.4</version>
  <description>A collection of ROS utilities for using WebRTC with ROS</description>

  <author email="chitiva@fly4future.com">Cristian Chitiva</author>
  <maintainer email="spurny@fly4future.com">Vojtech Spurny</maintainer>

  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>

  <depend>libgstreamer1.0-dev</depend>
  <depend>libgstreamer-plugins-base1.0-dev</depend>
  <depend>libgstreamer-plugins-bad1.0-dev</depend>  <!-- For webrtc plugin -->
  <exec_depend>gstreamer1.0-nice</exec_depend>

  <depend>nlohmann-json-dev</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
