<?xml version="1.0"?>
<package format="3">
  <name>webrtc_ros</name>
  <version>59.0.4</version>
  <description>A collection of ROS utilities for using WebRTC with ROS</description>

  <author email="chitiva@fly4future.com">Cristian Chitiva</author>
  <maintainer email="spurny@fly4future.com">Vojtech Spurny</maintainer>

  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>image_transport</depend>

  <!-- sudo apt-get update && sudo apt-get install -y gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools -->
  <depend>libgstreamer1.0-dev</depend>
  <depend>libgstreamer-plugins-base1.0-dev</depend>

  <depend>nlohmann-json-dev</depend>

  <buildtool_depend>rosidl_default_generators</buildtool_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
